### ISSUE TITLE
E_SETUP_DISCONNECT in case of reinstalling cafebazaar app

### ISSUE THREAD

**Issue by barghi** [ArioAtlas/react-native-cafe-bazaar#10]
Hi !
We faced an issue that relates to reinstalling cafebazar app. 
After installing our app from cafebazar the library works good in purchase but after uninstalling and installing cafebazar app, the purchase function returns E_SETUP_DISCONNECT .
The phone must be restarted to perform purchase correctly again.

**Comment by sam9010** [comment]
cafeBazaar Not install, please install it and so try again

**Comment by sam9010** [comment]
i have this error
but I noticed that I did not have cafe bazaar app installation

**Comment by arashmilani** [comment]
@contoriel @barghi Guys, do you think this is something about this library of it is something related to Cafebazaar itself?
