### ISSUE TITLE
Can't change DEVELOPER_PAYLOAD

### ISSUE THREAD

**Issue by seriiix** [ArioAtlas/react-native-cafe-bazaar#14]
It seems I can't change `DEVELOPER_PAYLOAD` param when I send a request to Baazar. Anything I pass to `DEVELOPER_PAYLOAD` will not change the default value of it which is "DEVELOPER_PAYLOAD". This is the piece of code I'm using:
```
CafeBazaar.open()
  .then(() => CafeBazaar.purchase(sku, 'something_else', 16))
  .then(details => {
    console.log(details)
    return CafeBazaar.close()
  })
  .catch(err => {
    console.log('CafeBazaar err:', err)
  })
```

The result is always:
```
{"mDeveloperPayload":"DEVELOPER_PAYLOAD","mItemType":"inapp","mOrderId":"lwl0n4mnS_0ZbFD5","mOriginalJson":"{\"orderId\": \"lwl0n4mnS_0ZbFD5\", \"purchaseToken\": \"lwl0n4mnS_0ZbFD5\", \"developerPayload\": \"DEVELOPER_PAYLOAD\", \"packageName\": \"com.rndfd\", \"purchaseState\": 0, \"purchaseTime\": 1559387190075, \"productId\": \"test\"}","mPackageName":"com.rndfd","mSignature":"k6QKh7hCFnV8uvJJJSvbdmXg5z25acJNq/bhhGJ2DFD/YLTeUaOglZTyVuN94qt1pQFNkpDFDQ8CS26K1k268it+Yy6ROEfGf6k1vbcz0zMlQlV93P0IPx5mDS+z1+6Jbjv9va0biy+FMxJ3JYz5yIYzCcy3ZeUFv+2/PI3tA9XNMer/iuCsn2Y4cUQlzyR46f4UpxxTlnXqANDrS+fueKGT4AbUGmaY6GeLxYnD","mSku":"test","mToken":"lwl0n4mnS_0ZbFD5","mPurchaseTime":1559387190075,"mPurchaseState":0}
```

**Comment by arashmilani** [comment]
We don't have any hard-coded `DEVELOPER_PAYLOAD` in this package. Can you search you project for any instance of that string?

**Comment by seriiix** [comment]
Thanks for the quick reply! I searched through the whole project and didn't find anything! Additionally, I created a new fresh project and the problem was still there.

**Comment by seriiix** [comment]
I recreated my app in baazar also recreated a new client and reinstalled this package. The problem is now gone. I'm pretty sure i miss config-ed something and this package is alright. Thanks for the help!
