### ISSUE TITLE
open() error: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by HessiPard** [ArioAtlas/react-native-cafe-bazaar#15]
Hi,
After upgrading react native to v 0.59.10, open() method doesn't work anymore. it results with following message:
`E_PURCHASE_ERROR Can only use lower 16 bits for requestCode`

**Comment by HessiPard** [comment]
I solved it. in case if you faced it too:
i implemented purchase method with this line of code:
`CafeBazaar.purchase(item.sku, 'someText', 123456)`
and it was working before upgrading react native.
then i just lower the developer_payload from 123456 to 123 and the error gone.
Good_Luck.

**Comment by arashmilani** [comment]
Thanks for reporting back the fix. Just a correction, the third parameter is `RC_REQUEST` not the `DEVELOPER_PAYLOAD`.
