### ISSUE TITLE
how to consume a product after purchasing (but not immediately)

### ISSUE THREAD

**Issue by bodaghialib4** [ArioAtlas/react-native-cafe-bazaar#21]
Hi,
I am using your module to use InApp Billing for Cafe Bazaar. 
It works correctly if the purchased product consumes immediately. But if after purchasing could not consume the product immediately, the problem occurs.
The loadOwnedItems return an empty array. If I try to re-purchase that product, it response that you purchased it previously and if I try to consume the previously purchased product, its response is that "you need to purchase the product first".
any suggestions, please?

**Comment by c0mm4nDer** [comment]
Me too!
I uninstall/ install cafebazaar app. after it login again then call loadOwnedItems. now I can get result. so consume work perfectly. but if try purchase items that already not consume problem show up!! 

I think this problem came from cafebazaar app. but Is so hard manage this situation.

**Comment by mahdir1995** [comment]
Any solution?

**Comment by arashmilani** [comment]
It seems this is not related to this package but this is a CafeBazar situation as these responses are being fetched from their API. Correct me if I'm wrong.
