### ISSUE TITLE
Error when call open

### ISSUE THREAD

**Issue by mahdimotamedi** [ArioAtlas/react-native-cafe-bazaar#22]
in the latest version of React Native: "0.61.5"
after and try to call "Open" an error happen.
"open is not a member of undefined" (it seems an unsupported modules because it's non gradle module)

**Comment by arashmilani** [comment]
Currently we (the maintainers) don't have the time to update the library for the latest React Native version. Any pull request is appreciated.

**Comment by mahdimotamedi** [comment]
Problem resolved. it was because of android studio caches.
