### ISSUE TITLE
does not work in react native ver 0.63.2

### ISSUE THREAD

**Issue by milad-kh** [ArioAtlas/react-native-cafe-bazaar#27]
Could not resolve project :react-native-cafe-bazaar.

![image](https://user-images.githubusercontent.com/10386918/92268748-3d8a5f00-eef8-11ea-876e-1350e28717ad.png)

**Comment by 2navidmasoudi** [comment]
Add this line to your _settings.gradle_
`project(':react-native-cafe-bazaar').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-cafe-bazaar/android/app')`

If you got a problem like this one:

java.lang.RuntimeException: Duplicate class 
org.intellij.lang.annotations.Identifier

then add this line to _app/build.gradle_

```
configurations {
    cleanedAnnotations
        compile.exclude group: 'org.jetbrains' , module:'annotations'
}
```
Don't forget to clean your build folder

`$ cd android && ./gradlew clean && cd .. && npx react-native run android`

Good luck!

**Comment by arashmilani** [comment]
This library is not being actively updated. You might want to use the [RN library of the cafebazaar itself](https://github.com/cafebazaar/react-native-poolakey).
