### ISSUE TITLE
Purchase response

### ISSUE THREAD

**Issue by reza-madani** [ArioAtlas/react-native-cafe-bazaar#28]
` 
...
await CafeBazaar.open();
const details = await CafeBazaar.purchase(`${productId}`,'"payload", 2);
const callback = JSON.parse(details);
...
`
Please add to the document JSON.parse() requirement.

**Comment by arashmilani** [comment]
This library is not being actively updated. You might want to use the [RN library of the cafebazaar itself](https://github.com/cafebazaar/react-native-poolakey).
