### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by pouyarahmti** [ArioAtlas/react-native-cafe-bazaar#29]
Cannot run it in react native 0.63. I faced this error.

> Could not resolve all task dependencies for configuration ':react-native-cafe-bazaar:debugCompileClasspath'.
   > Could not find androidx.appcompat:appcompat:1.0.2.
     Required by:
         project :react-native-cafe-bazaar > com.facebook.react:react-native:0.63.3
   > Could not find androidx.versionedparcelable:versionedparcelable:1.0.0.       
     Required by:
         project :react-native-cafe-bazaar > androidx.core:core:1.0.0

**Comment by arashmilani** [comment]
This library is not being actively updated. You might want to use the [RN library of the cafebazaar itself](https://github.com/cafebazaar/react-native-poolakey).
