### ISSUE TITLE
Does not work on some Xiomi phones

### ISSUE THREAD

**Issue by pouyarahmti** [ArioAtlas/react-native-cafe-bazaar#30]
According to cafe bazzar documents, you need to update IABHelper and AIDL files in order to work on all type of phones. please update them or let me know how to do it. thanks.

**Comment by arashmilani** [comment]
Pourya jan, you can always send a pull request with these changes and indeed it is appreciated.

**Comment by pouyarahmti** [comment]
Hello Again. You just need to update IABHelper and Aidl files. just replace them with files in the link below.
http://github.com/congenialmobile/TrivialDrive/archive/master.zip
and everything is good to go.

**Comment by pouyarahmti** [comment]
There is a pull request that have done the same thing. Hope you will accept it to keep everything up to date

**Comment by arashmilani** [comment]
Dear Pourya It seems you have deleted your fork of the project so the pull request can not be merged.

**Comment by arashmilani** [comment]
This library is not being actively updated. You might want to use the [RN library of the cafebazaar itself](https://github.com/cafebazaar/react-native-poolakey).
