### ISSUE TITLE
What to set RC_REQUEST to?

### ISSUE THREAD

**Issue by HessiPard** [ArioAtlas/react-native-cafe-bazaar#4]
Hi ... Good job for this great package!
I just want to know the use of RC_REQUEST and how must we deal with that?
I reviewed official bazaar doc and this package native code but didn't find out anything.

**Comment by contoriel** [comment]
Hi, thanks for downloading the package.
RC_REQUEST is an arbitrary integer, and we use it for validating the purchase request.

**Comment by HessiPard** [comment]
thanks for replying ...
for every purchase flow user starts I just call `Cafebazar.open()` at the first and `Cafebazar.close()` at the end. (Best practice based on this package readme).
So it doesnt make sense to define an extra integer for helper class to determine the purchase flow and proper result for requests because there is only one active purchase flow at a time and it must be.

**Comment by contoriel** [comment]
you are right. because the package handles the purchase flow, there is no need for passing RC_REQUEST. we will remove it in next update. meanwhile, you can pass any arbitrary integer to use purchase methods.
